apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      release: v1
  template:
    metadata:
      labels:
        app: frontend
        release: v1
    spec:
      containers:
      - image: gcr.io/google-samples/hello-app:1.0
        imagePullPolicy: IfNotPresent
        name: frontend-app
        ports:
        - containerPort: 80
          protocol: TCP
        resources: 
          limits:
            cpu: 20m
            memory: 50Mi
          requests:
            cpu: 20m
            memory: 50Mi  
