apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-blue
      release: v2
  template:
    metadata:
      labels:
        app: frontend-blue
        release: v2
    spec:
      containers:
        - image: lxqhim/smart-bank-frontend:blue
          imagePullPolicy: IfNotPresent
          name: frontend-blue
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 10m
              memory: 30Mi
            requests:
              cpu: 10m
              memory: 30Mi
