apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-green
      release: v1
  template:
    metadata:
      labels:
        app: frontend-green
        release: v1
    spec:
      containers:
        - image: abhay1813/finalfrontend
          imagePullPolicy: IfNotPresent
          name: frontend-green
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 20m
              memory: 50Mi
            requests:
              cpu: 20m
              memory: 50Mi
